### PR TITLE
Repository optimization

### PR DESCRIPTION
**Pull request by IAHM-COL**
As in the previous case, executables are removed, as in SVN rev 497

### CODE REVIEW

**Comment by IAHM-COL** [comment]
Dear JWocky

The repos are currently out of sync
This pull request only change in in the executable flag of 2 files. 

Best,
IH-COL

**Comment by JWocky** [comment]
Uh, there are bigger things coming with the 767 and the B-52, so does 
that interfere somehow?

**Comment by IAHM-COL** [comment]
No. Just updating the repos here.
The JPack in FGMEMBERs and yours differ. 
You can treat this whenever you get some time. I am just leaving a "sticky note" reminder

**Comment by JWocky** [comment]
Okay, I'm still shoveling instruments around

**Pull request merged**
